project:
  type: website

website:
  title: "DataTax R Course"
  navbar:
    search: true
    left:
      - text: "Home"
        href: index.html  # Ensure this points to `.html` not `.qmd`
      - text: "Slides"
        menu:
          - text: "Introduction to R"
            href: 1_introduction_to_r.html  # `.html` for web link
          - text: "Data Import/Export"
            href: 2_import_export.html 

format:
  html:
    include-in-header: styles.css  # Assuming you have styles.css in your project directory
    theme: flatly
    allow-html: true

title: "DataTax R Course"
author: "DataTax (Ruggero Doino, Thiago Scott)"
version: 0.0.1
quarto-required: ">=1.3.361"

# Contributes Section
contributes:
  revealjs-plugins:
    - name: RevealHighlightword
      script:
        - highlightword.js

formats:
  revealjs:
    theme: _extensions/dime-worldbank/dime/dime.scss
    slide-number: c/t
    highlight-style: atom-one
    show-slide-number: all
    title-slide-attributes:
      data-background-color: "#FFFFFF"
    preview-links: true
    include-in-header: favicon.html

    