project:
  type: website

website:
  title: "DataTax R Course"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Slides"
        menu:
          - text: "Introduction to R"
            href: 1_Introduction_to_R.qmd
          - text: "Data Import/Export"
            href: 2_import_export.qmd
    right:
      - text: ""
format:
  html:
    allow-html: true
    theme: flatly

title: "DataTax R Course"
author: "DataTax (Ruggero Doino, Thiago Scott)"
version: 0.0.1
quarto-required: ">=1.3.361"

# Contributes Section
contributes:
  revealjs-plugins:
    - name: RevealHighlightword
      script:
        - highlightword.js

formats:
  revealjs:
    theme: dime.scss
    slide-number: c/t
    highlight-style: atom-one
    show-slide-number: all
    title-slide-attributes:
      data-background-color: "#FFFFFF"
    preview-links: true
    include-in-header: favicon.html