project:
  type: website

website:
  title: "DataTax R Course"
  sidebar:
    style: "docked"
    contents:
      - section: "Lessons:"
        contents:
          - text: "Introduction to R"
            href: 1_introduction_to_r.html  # `.html` for web link
          - text: "Data Import/Export"
            href: 2_import_export.html 

  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: journal
    linkcolor: "#ba0202"
    css: styles.css
    toc: true
    highlight-style: github
    navbar-bg: "#ba0202"  # Add navbar background color here
    navbar-text-color: "#faf7f7"  # Navbar text color

